# Generated by Django 4.2.6 on 2024-02-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0007_useraccount_bio_useraccount_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='profile_pic',
        ),
    ]
