# Generated by Django 4.2.6 on 2024-02-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0008_remove_useraccount_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_pic',
            field=models.ImageField(default='avatar.png', upload_to='images/'),
        ),
    ]
