# Generated by Django 4.2.6 on 2024-02-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0010_remove_profile_author_profile_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
