# Generated by Django 4.2.6 on 2024-02-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0011_alter_useraccount_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
