# Generated by Django 4.2.6 on 2024-03-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0014_alter_profile_account_alter_useraccount_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tracks',
            new_name='track',
        ),
    ]
