# Generated by Django 4.2.6 on 2024-03-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0015_rename_tracks_profile_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
