# Generated by Django 4.2.6 on 2024-03-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0020_useraccount_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='artistname',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
