# Generated by Django 4.2.6 on 2024-03-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0021_useraccount_artistname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='artistname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
