# Generated by Django 4.2.6 on 2024-03-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0022_alter_useraccount_artistname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error404e',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgrounderror', models.ImageField(upload_to='images/')),
                ('texterror', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
