# Generated by Django 4.2.6 on 2024-03-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0023_error404e'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Error404e',
        ),
    ]
