# Generated by Django 4.2.6 on 2024-03-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0025_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
