# Generated by Django 4.2.6 on 2024-03-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0027_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
