# Generated by Django 4.2.6 on 2024-03-09 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0028_comment_slug_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post1', to='userartist.profile'),
            preserve_default=False,
        ),
    ]
