# Generated by Django 4.2.6 on 2024-03-09 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0031_remove_comment_post1'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post1',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='post1', to='userartist.profile'),
            preserve_default=False,
        ),
    ]
