# Generated by Django 4.2.6 on 2024-03-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0042_comment_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='uuid',
        ),
    ]
