# Generated by Django 4.2.6 on 2024-03-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0045_alter_profile_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='key',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ky',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
