# Generated by Django 4.2.6 on 2024-03-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0046_profile_key_profile_ky_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ky',
            field=models.SlugField(),
        ),
    ]
