# Generated by Django 4.2.6 on 2024-03-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0049_remove_profile_key_remove_profile_ky'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='key',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ky',
            field=models.SlugField(null=True),
        ),
    ]
