# Generated by Django 4.2.6 on 2024-02-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Uploadmusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('adamid', models.SlugField()),
                ('lyrics', models.TextField()),
                ('ky', models.SlugField()),
                ('image', models.ImageField(upload_to='images/')),
                ('genre', models.CharField(max_length=100)),
                ('track', models.FileField(upload_to='music/')),
                ('slug', models.SlugField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='uploadmusic.category')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('track', 'title', 'id')},
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField()),
                ('slug', models.SlugField()),
                ('Artistimage', models.ImageField(upload_to='images/')),
                ('adamid', models.SlugField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='uploadmusic.uploadmusic')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('artist', 'order', 'id')},
            },
        ),
    ]
