# Generated by Django 4.2.6 on 2024-03-10 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('uploadmusic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmusic',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
