# Generated by Django 4.2.6 on 2024-03-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadmusic', '0002_uploadmusic_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmusic',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
