# Generated by Django 4.2.6 on 2024-03-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadmusic', '0003_remove_uploadmusic_category_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
